### create request
POST http://54.147.182.132:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Arjun Mehta",
  "email": "arjun.mehta.devvv79@example.com",
  "address": "Baner, Pune, Maharashtra",
  "dateOfBirth": "1992-11-03"
}