apiVersion: v1
kind: Secret
metadata:
  name: patient-management-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded values. 
  # POSTGRES_PASSWORD = password
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  # JWT_SECRET = supersecretkey
  JWT_SECRET: c3VwZXJzZWNyZXRrZXk=
