apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-db-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
  namespace: default
spec:
  serviceName: "auth-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "db"
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: patient-management-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: patient-management-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: auth-db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: auth-db-data
        persistentVolumeClaim:
          claimName: auth-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db-service
  namespace: default
spec:
  selector:
    app: auth-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
