###

POST http://54.147.182.132:4004/auth/login
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "password123"

}

> {% client.global.set("token", response.body.token) %}